# Filebeat configuration for OOTS E2E Testing
# Collects all Bridge logs (APP, EXT, OOTS) from log files

filebeat.inputs:
  # APP logs - operational events
  - type: log
    id: app-logs
    enabled: true
    paths:
      - /var/log/bridge/app-logs.log
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true
      expand_keys: true
    fields:
      log.source: oots-bridge
    fields_under_root: true

  # OOTS logs - protocol messages
  - type: log
    id: oots-logs
    enabled: true
    paths:
      - /var/log/bridge/oots-logs.log
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true
      expand_keys: true
    fields:
      log.source: oots-bridge
    fields_under_root: true

  # EXT logs - external service events (EMREX)
  - type: log
    id: ext-logs
    enabled: true
    paths:
      - /var/log/bridge/ext-logs.log
    json:
      keys_under_root: true
      overwrite_keys: true
      add_error_key: true
      expand_keys: true
    fields:
      log.source: oots-bridge
    fields_under_root: true

processors:
  - timestamp:
      field: "@timestamp"
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2024-01-15T10:30:00.000Z'
  - drop_fields:
      fields: ["agent", "ecs", "host", "input"]
      ignore_missing: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "oots-logs-%{+yyyy.MM.dd}"

setup.template:
  name: "oots-logs"
  pattern: "oots-logs-*"
  enabled: true
  settings:
    index:
      number_of_shards: 1
      number_of_replicas: 0

setup.ilm:
  enabled: false

logging.level: info
logging.to_files: false
