# https://taskfile.dev
version: "3"

vars:
  BRIDGE_REPO: ../oots-bridge-monorepo

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  # ==========================================================================
  # Setup Tasks
  # ==========================================================================

  setup:
    desc: "Run all setup tasks (keystores + domibus + bridge image)"
    cmds:
      - task: setup:keystores
      - task: setup:domibus
      - task: setup:bridge-image

  setup:keystores:
    desc: "Generate Domibus keystores for blue and red gateways"
    dir: domibus/scripts
    cmds:
      - ./generate-keystores.sh
    status:
      - test -f ../conf/keystores/gateway_keystore.p12
      - test -f ../conf-red/keystores/gateway_keystore.p12

  setup:domibus:
    desc: "Download Domibus DDL and WS plugin"
    cmds:
      - ./scripts/setup-e2e.sh
    status:
      - test -f domibus/sql/mysql-5.1.9.ddl
      - test -f domibus/conf/plugins/lib/domibus-default-ws-plugin-5.1.9.jar

  setup:bridge-image:
    desc: "Build bridge image from feature branch"
    dir: "{{.BRIDGE_REPO}}"
    cmds:
      - echo "Building monorepo base image..."
      - docker build -t oots-emrex/monorepo:latest -f Dockerfile .
      - echo "Building bridge backend image..."
      - docker build -t oots-bridge:latest -f apps/bridge/backend/Dockerfile .

  # ==========================================================================
  # Full E2E Stack (Red/Blue Domibus + Bridge + ELK)
  # ==========================================================================

  e2e:start:
    desc: "Start complete E2E stack with single command"
    deps: [setup:keystores, setup:domibus]
    cmds:
      - echo "Starting OOTS E2E Stack..."
      - docker compose -f docker-compose.e2e.yml up -d
      - echo ""
      - echo "Waiting for services to be healthy..."
      - |
        echo "This may take 2-3 minutes for Domibus to initialize..."
        BLUE_RESTARTS=0
        RED_RESTARTS=0
        for i in $(seq 1 60); do
          BLUE_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' domibus-blue 2>/dev/null || echo "missing")
          RED_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' domibus-red 2>/dev/null || echo "missing")
          ES_HEALTHY=$(docker inspect --format='{{.State.Health.Status}}' es-e2e 2>/dev/null || echo "missing")

          echo "[$i/60] Blue: $BLUE_HEALTHY | Red: $RED_HEALTHY | ES: $ES_HEALTHY"

          if [ "$BLUE_HEALTHY" = "healthy" ] && [ "$RED_HEALTHY" = "healthy" ] && [ "$ES_HEALTHY" = "healthy" ]; then
            echo ""
            echo "All services are healthy!"
            break
          fi

          # Restart unhealthy Domibus containers (they don't auto-recover from MySQL race)
          if [ "$BLUE_HEALTHY" = "unhealthy" ] && [ $BLUE_RESTARTS -lt 2 ]; then
            echo "  Restarting domibus-blue..."
            docker restart domibus-blue >/dev/null 2>&1
            BLUE_RESTARTS=$((BLUE_RESTARTS + 1))
          fi
          if [ "$RED_HEALTHY" = "unhealthy" ] && [ $RED_RESTARTS -lt 2 ]; then
            echo "  Restarting domibus-red..."
            docker restart domibus-red >/dev/null 2>&1
            RED_RESTARTS=$((RED_RESTARTS + 1))
          fi

          if [ $i -eq 60 ]; then
            echo ""
            echo "WARNING: Some services may not be fully ready yet."
            echo "Check status with: task e2e:status"
          fi

          sleep 5
        done
      - task: e2e:setup-elasticsearch
      - task: e2e:setup-kibana
      - task: e2e:configure-domibus
      - task: e2e:upload-pmodes
      - |
        echo ""
        echo "=========================================="
        echo "OOTS E2E Stack is ready!"
        echo "=========================================="
        echo ""
        echo "Admin Consoles:"
        echo "  Blue Gateway: http://localhost:8180/domibus"
        echo "  Red Gateway:  http://localhost:8280/domibus"
        echo "  Credentials:  admin / 123456"
        echo ""
        echo "Monitoring:"
        echo "  Kibana:       http://localhost:5601"
        echo "  Bridge:       https://localhost:3443"
        echo ""
        echo "Send test request:"
        echo "  task e2e:trigger"

  e2e:stop:
    desc: "Stop E2E stack"
    cmds:
      - docker compose -f docker-compose.e2e.yml down

  e2e:clean:
    desc: "Stop containers and remove volumes (fresh start)"
    cmds:
      - docker compose -f docker-compose.e2e.yml down -v --remove-orphans

  e2e:nuke:
    desc: "Complete cleanup - remove containers, volumes, images, and keystores"
    cmds:
      - docker compose -f docker-compose.e2e.yml down -v --remove-orphans
      - docker rmi oots-bridge:latest oots-emrex/monorepo:latest oots-bridge-monorepo-testing-mock-emrex:latest 2>/dev/null || true
      - rm -rf domibus/conf/keystores/* domibus/conf-red/keystores/*
      - echo "All E2E resources removed. Run 'task setup && task e2e:start' to rebuild."

  e2e:rebuild:
    desc: "Rebuild all images (bridge + mock-emrex) without restarting stack"
    cmds:
      - task: setup:bridge-image
      - task: e2e:rebuild:mock-emrex

  e2e:rebuild:bridge:
    desc: "Rebuild and restart only the Bridge container"
    cmds:
      - task: setup:bridge-image
      - docker compose -f docker-compose.e2e.yml up -d bridge
      - echo "Waiting for Bridge to be healthy..."
      - |
        for i in $(seq 1 30); do
          STATUS=$(docker inspect --format='{{.State.Health.Status}}' oots-bridge 2>/dev/null || echo "missing")
          echo "[$i/30] Bridge: $STATUS"
          if [ "$STATUS" = "healthy" ]; then
            echo "Bridge is ready!"
            break
          fi
          sleep 2
        done
      - docker compose -f docker-compose.e2e.yml up -d bridge-proxy filebeat

  e2e:rebuild:mock-emrex:
    desc: "Rebuild and restart only the mock-emrex container"
    cmds:
      - docker compose -f docker-compose.e2e.yml build --no-cache mock-emrex
      - docker compose -f docker-compose.e2e.yml up -d mock-emrex
      - echo "Mock EMREX restarted"

  e2e:rebuild:all:
    desc: "Rebuild all images and restart the entire stack"
    cmds:
      - task: e2e:rebuild
      - task: e2e:restart

  e2e:fresh:
    desc: "Full reset: nuke everything, rebuild images, start fresh stack"
    cmds:
      - task: e2e:nuke
      - task: setup
      - task: e2e:start

  e2e:restart:
    desc: "Clean restart - remove volumes and start fresh"
    cmds:
      - task: e2e:clean
      - task: e2e:start

  e2e:status:
    desc: "Show E2E stack status"
    cmds:
      - docker compose -f docker-compose.e2e.yml ps

  e2e:logs:
    desc: "Follow all E2E logs"
    cmds:
      - docker compose -f docker-compose.e2e.yml logs -f

  e2e:logs:blue:
    desc: "Follow Blue Gateway logs"
    cmds:
      - docker compose -f docker-compose.e2e.yml logs -f domibus-blue

  e2e:logs:red:
    desc: "Follow Red Gateway logs"
    cmds:
      - docker compose -f docker-compose.e2e.yml logs -f domibus-red

  e2e:logs:bridge:
    desc: "Follow Bridge logs"
    cmds:
      - docker compose -f docker-compose.e2e.yml logs -f bridge

  e2e:logs:bridge:app:
    desc: "View Bridge APP logs (structured JSON)"
    cmds:
      - 'docker exec oots-bridge cat /app/logs/app-logs.log 2>/dev/null | tail -20 | jq -c ''{action: .["event.action"], outcome: .["event.outcome"], error: .["error.message"]}'''

  e2e:logs:bridge:ext:
    desc: "View Bridge EXT logs (external system interactions)"
    cmds:
      - 'docker exec oots-bridge cat /app/logs/ext-logs.log 2>/dev/null | tail -20 | jq -c ''{action: .["event.action"], outcome: .["event.outcome"], sessionId: .["app.sessionId"]}'''

  e2e:logs:bridge:oots:
    desc: "View Bridge OOTS logs (evidence request/response)"
    cmds:
      - 'docker exec oots-bridge cat /app/logs/oots-logs.log 2>/dev/null | tail -20 | jq -c ''{action: .["event.action"], outcome: .["event.outcome"], convId: .["oots.conversation.id"]}'''

  e2e:logs:mock-emrex:
    desc: "View Mock EMREX logs"
    cmds:
      - 'docker logs mock-emrex --tail 20 2>&1 | grep -v "Warning:" | jq -c ''{action: .["event.action"], outcome: .["event.outcome"], sessionId: .["app.sessionId"]}'' 2>/dev/null || docker logs mock-emrex --tail 20'

  e2e:setup-elasticsearch:
    desc: "Setup Elasticsearch with OOTS index template"
    cmds:
      - ./scripts/setup-elasticsearch.sh

  e2e:setup-kibana:
    desc: "Setup Kibana with OOTS dashboard"
    cmds:
      - ./scripts/setup-kibana.sh

  e2e:configure-domibus:
    desc: "Configure Domibus users and roles"
    cmds:
      - ./scripts/configure-domibus.sh

  e2e:upload-pmodes:
    desc: "Upload PModes to both gateways via REST API"
    cmds:
      - ./scripts/upload-pmode.sh

  e2e:trigger:
    desc: "Send a test OOTS request through the system"
    cmds:
      - ./scripts/trigger-request.sh

  e2e:validate:
    desc: "Validate structured logs in Elasticsearch"
    cmds:
      - npx tsx scripts/validate.ts

  e2e:test:
    desc: "Run all path coverage tests"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts

  e2e:test:path:
    desc: "Run a specific path test (usage: task e2e:test:path -- 2)"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path={{.CLI_ARGS}} --skip-prereqs

  e2e:test:1:
    desc: "Path 1: Happy Path (Preview Required)"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=1 --skip-prereqs

  e2e:test:2:
    desc: "Path 2: Happy Path (Evidence Delivered)"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=2 --skip-prereqs

  e2e:test:3:
    desc: "Path 3: No Preview Support"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=3 --skip-prereqs

  e2e:test:4:
    desc: "Path 4: Request XML Validation Error"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=4 --skip-prereqs

  e2e:test:5:
    desc: "Path 5: Request Schematron Error"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=5 --skip-prereqs

  e2e:test:6:
    desc: "Path 6: EMREX User Cancellation"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=6 --skip-prereqs

  e2e:test:7:
    desc: "Path 7: EMREX Provider Error"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=7 --skip-prereqs

  e2e:test:8:
    desc: "Path 8: EMREX No Results"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=8 --skip-prereqs

  e2e:test:9:
    desc: "Path 9: EMREX Invalid GZIP"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=9 --skip-prereqs

  e2e:test:10:
    desc: "Path 10: EMREX Invalid XML"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=10 --skip-prereqs

  e2e:test:11:
    desc: "Path 11: EMREX Identity Mismatch"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=11 --skip-prereqs

  e2e:test:12:
    desc: "Path 12: Session Timeout"
    cmds:
      - npx tsx scripts/path-coverage-tests.ts --path=12 --skip-prereqs

  e2e:clear-logs:
    desc: "Clear all logs from Elasticsearch (fresh test run)"
    cmds:
      - |
        INDEX=$(curl -s "http://localhost:9200/_cat/indices/oots*?h=index" | head -1)
        if [ -n "$INDEX" ]; then
          curl -s -X DELETE "http://localhost:9200/$INDEX" | jq .
          echo "Cleared index: $INDEX"
        else
          echo "No oots-logs index found"
        fi

  e2e:test:fresh:
    desc: "Clear logs and run all path tests (clean test run)"
    cmds:
      - task: e2e:clear-logs
      - sleep 2
      - task: e2e:test

  e2e:test:verify:
    desc: "Rebuild bridge, clear logs, run all tests (full verification cycle)"
    cmds:
      - task: e2e:rebuild:bridge
      - task: e2e:clear-logs
      - sleep 2
      - task: e2e:test

  e2e:health:
    desc: "Quick health check of all services"
    cmds:
      - |
        echo "Service Health Status:"
        echo "======================"
        for svc in domibus-blue domibus-red oots-bridge mock-emrex es-e2e; do
          STATUS=$(docker inspect --format='{{`{{.State.Health.Status}}`}}' $svc 2>/dev/null || echo "not running")
          printf "  %-15s %s\n" "$svc:" "$STATUS"
        done
        echo ""
        echo "Quick connectivity test:"
        curl -sf http://localhost:3003/health > /dev/null && echo "  Bridge:     OK" || echo "  Bridge:     FAIL"
        curl -sf http://localhost:9081/health > /dev/null && echo "  Mock EMREX: OK" || echo "  Mock EMREX: FAIL"
        curl -sf http://localhost:9200/_cluster/health > /dev/null && echo "  ES:         OK" || echo "  ES:         FAIL"

  # ==========================================================================
  # Legacy Single Domibus Stack (for backward compatibility)
  # ==========================================================================

  domibus:start:
    desc: "Start single Domibus stack (legacy)"
    deps: [setup:keystores]
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.domibus.yml up -d
      - echo "Waiting for services to be healthy..."
      - sleep 30
      - docker compose -f docker-compose.yml -f docker-compose.domibus.yml ps

  domibus:stop:
    desc: "Stop single Domibus stack (legacy)"
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.domibus.yml down

  domibus:logs:
    desc: "Follow single Domibus logs"
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.domibus.yml logs -f domibus

  domibus:clean:
    desc: "Remove all single Domibus volumes"
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.domibus.yml down -v

  # ==========================================================================
  # Log Generation & Testing (State 3 Pipeline)
  # ==========================================================================

  generate-logs:
    desc: "Generate test logs from structured logging functions"
    cmds:
      - npm run generate-logs
    sources:
      - scripts/generate-logs.ts
      - "{{.BRIDGE_REPO}}/apps/bridge/backend/src/utils/oots-logs/*.ts"
    generates:
      - testdata/raw_logs.ndjson

  test:pipeline:
    desc: "Test ingest pipeline with generated logs"
    deps: [generate-logs]
    cmds:
      - docker compose up -d elasticsearch
      - echo "Waiting for Elasticsearch..."
      - sleep 15
      - |
        curl -s -X PUT "http://localhost:9200/_ingest/pipeline/oots-state3-ecs" \
          -H "Content-Type: application/json" \
          -d @../oots-logging-states/state3-otel/pipeline/ingest-pipeline.json
      - |
        # Convert to bulk format and ingest
        while IFS= read -r line; do
          echo '{"index":{"_index":"oots-test"}}'
          echo "$line"
        done < testdata/raw_logs.ndjson > /tmp/bulk.ndjson
        curl -s -X POST "http://localhost:9200/_bulk?pipeline=oots-state3-ecs" \
          -H "Content-Type: application/x-ndjson" \
          --data-binary @/tmp/bulk.ndjson | jq '{errors, items: (.items | length)}'
      - |
        echo "Verifying fields..."
        curl -s "http://localhost:9200/oots-test/_search?size=1" | \
          jq '.hits.hits[0]._source | {oots_result: .oots.result, event, transaction, messaging}'

  # ==========================================================================
  # Cleanup
  # ==========================================================================

  clean:
    desc: "Clean up all containers, volumes, and generated files"
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.domibus.yml down -v 2>/dev/null || true
      - docker compose -f docker-compose.e2e.yml down -v 2>/dev/null || true
      - rm -f testdata/*.ndjson testdata/*.log
      - rm -rf domibus/conf/keystores/* domibus/conf-red/keystores/*
